SELECT
	DEPARTMENTS.DEPARTMENT_NAME,
	ROUND(AVG(EMPLOYEES.SALARY), 2) AS AVARAGE_SALARY
FROM
	DEPARTMENTS
	LEFT JOIN EMPLOYEES ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY
	DEPARTMENTS.DEPARTMENT_NAME
HAVING
	AVG(EMPLOYEES.SALARY) < (
		SELECT
			AVG(SALARY)
		FROM
			EMPLOYEES
	)