SELECT
    M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
    E.SUM_SALARY
FROM
    EMPLOYEES M
    JOIN (
        SELECT
            SUM(E.SALARY) AS SUM_SALARY,
            AVG(E.SALARY) AS AVG_SALARY,
            E.MANAGER_ID
        FROM
            EMPLOYEES E
        GROUP BY
            E.MANAGER_ID
    ) E ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY
    E.AVG_SALARY DESC