SELECT 
    M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
    SUM(E.SALARY) AS TOTAL_SALARY
FROM 
    EMPLOYEES E
JOIN 
    EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY 
    M.EMPLOYEE_ID, M.FIRST_NAME, M.LAST_NAME
HAVING 
    (SELECT AVG(E2.SALARY)
     FROM EMPLOYEES E2
     WHERE E2.MANAGER_ID = M.EMPLOYEE_ID) IS NOT NULL
ORDER BY 
    (SELECT AVG(E2.SALARY)
     FROM EMPLOYEES E2
     WHERE E2.MANAGER_ID = M.EMPLOYEE_ID) DESC
