SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	LEFT JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE
	SALARY IN (
		SELECT
			SALARY
		FROM
			EMPLOYEES
		WHERE
			FIRST_NAME = 'Alexander'
	)