SELECT
	EMPLOYEES.EMPLOYEE_ID,
	EMPLOYEES.FIRST_NAME,
	EMPLOYEES.LAST_NAME,
	JOBS.JOB_TITLE,
	EMPLOYEES.SALARY,
	SALARIES.MAX_SALARY
FROM
	EMPLOYEES
	LEFT JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
	LEFT JOIN (
		SELECT
			JOB_ID,
			MAX(SALARY) AS MAX_SALARY
		FROM
			EMPLOYEES
		GROUP BY
			JOB_ID
	) AS SALARIES ON SALARIES.JOB_ID = EMPLOYEES.JOB_ID
WHERE
	SALARIES.MAX_SALARY - EMPLOYEES.SALARY != 0