SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	J.JOB_TITLE,
	E.SALARY,
	MAX_SALARIES.MAX_SALARY,
	(MAX_SALARIES.MAX_SALARY - E.SALARY) AS SALARY_DIFFERENCE
FROM
	EMPLOYEES E
	JOIN JOBS J ON E.JOB_ID = J.JOB_ID
	JOIN (
		SELECT
			JOB_ID,
			MAX(SALARY) AS MAX_SALARY
		FROM
			EMPLOYEES
		GROUP BY
			JOB_ID
	) AS MAX_SALARIES ON E.JOB_ID = MAX_SALARIES.JOB_ID
WHERE
	(MAX_SALARIES.MAX_SALARY - E.SALARY) != 0