SELECT
    DEPARTMENTS.DEPARTMENT_NAME,
    COUNT(EMPLOYEES.EMPLOYEE_ID) AS COUNT_EMPLOYEES,
    ROUND(AVG(EMPLOYEES.SALARY), 2) AS AVARAGE_SALARY
FROM
    DEPARTMENTS
    LEFT JOIN EMPLOYEES ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY
    DEPARTMENTS.DEPARTMENT_NAME
HAVING
    AVG(EMPLOYEES.SALARY) > 10000