SELECT
    EMPLOYEES.EMPLOYEE_ID,
    JOBS.JOB_TITLE
FROM
    EMPLOYEES
    JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
    JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE
    SALARY > 5000
    AND DEPARTMENTS.DEPARTMENT_NAME = 'IT'