SELECT
    EMP.FIRST_NAME || ' ' || EMP.LAST_NAME AS EMPLOYEES_FULL_NAME,
    EMP.SALARY as employee_salary,
    MNG.FIRST_NAME || ' ' || MNG.LAST_NAME AS MANAGER_FULL_NAME,
    MNG.SALARY AS manager_salary,
    MNG.SALARY - EMP.SALARY AS DIFFERENCE_SALARY
FROM
    EMPLOYEES EMP
    LEFT JOIN EMPLOYEES MNG ON EMP.MANAGER_ID = MNG.EMPLOYEE_ID
WHERE
    MNG.SALARY - EMP.SALARY < mng.salary / 3
ORDER BY
    DIFFERENCE_SALARY DESC