SELECT
    EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS FULL_NAME,
    EMPLOYEES.SALARY,
    DEPARTMENTS.DEPARTMENT_NAME
FROM
    EMPLOYEES
    RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    LEFT JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
WHERE
    LOCATIONS.STATE_PROVINCE = 'Washington'