SELECT
    EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS FULL_NAME,
    JOBS.JOB_TITLE,
    EMPLOYEES.HIRE_DATE
FROM
    EMPLOYEES
    LEFT JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
WHERE
    EMPLOYEES.PHONE_NUMBER IS NULL