SELECT
    D.DEPARTMENT_NAME AS НАЗВАНИЕ_ОТДЕЛА,
    L.CITY AS ГОРОД,
    COUNT(DISTINCT E.EMPLOYEE_ID) AS КОЛИЧЕСТВО_СОТРУДНИКОВ,
    COUNT(DEP.DEPENDENT_ID) AS КОЛИЧЕСТВО_ДЕТЕЙ
FROM
    EMPLOYEES E
    LEFT JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
    LEFT JOIN DEPENDENTS DEP ON E.EMPLOYEE_ID = DEP.EMPLOYEE_ID
GROUP BY
    D.DEPARTMENT_NAME,
    L.CITY