SELECT
	EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS FULL_NAME,
	DEPARTMENTS.DEPARTMENT_NAME,
	LOCATIONS.CITY,
	REGIONS.REGION_NAME
FROM
	EMPLOYEES
	LEFT JOIN DEPARTMENTS USING (DEPARTMENT_ID)
	LEFT JOIN LOCATIONS USING (LOCATION_ID)
	LEFT JOIN COUNTRIES USING (COUNTRY_ID)
	LEFT JOIN REGIONS USING (REGION_ID)
WHERE
	EMPLOYEES.LAST_NAME LIKE '%o%'
