SELECT
    EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS FULL_NAME,
    DEPARTMENTS.DEPARTMENT_NAME,
    LOCATIONS.CITY,
    REGIONS.REGION_NAME
FROM
    EMPLOYEES
    LEFT JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
    LEFT JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
    LEFT JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
    LEFT JOIN REGIONS ON REGIONS.REGION_ID = COUNTRIES.REGION_ID
ORDER BY
    EMPLOYEES.LAST_NAME DESC